apiVersion: v1
kind: Template
metadata:
  annotations:
    description: ${SERVICE_NAME} build config template
  name: ${SERVICE_NAME}-build-config-template
parameters:
- description: Name of the service
  displayName: Service Name
  name: SERVICE_NAME
- description: Name of project
  displayName: Project Name
  name: PROJECT_NAME
- description: Target environment
  displayName: Environment
  name: ENVIRONMENT
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${SERVICE_NAME}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: ${SERVICE_NAME}
      spec:
        volumes:
        - name: config-volume
          configMap:
            name: ${SERVICE_NAME}-${ENVIRONMENT}-config
            items:
              - key: application.properties
                path: application.properties
            defaultMode: 420
        containers:
        - name: ${SERVICE_NAME}
          image: 172.30.1.1:5000/${PROJECT_NAME}/${SERVICE_NAME}
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 1
          name: ${SERVICE_NAME}
          volumeMounts:
          - name: config-volume
            mountPath: /opt/openshift/config
          ports:
          - containerPort: 3000
            protocol: TCP
          env:
          - name: ENVIRONMENT_NAME
            value: dev
          - name: TZ
            value: Pacific/Auckland
          resources:
            limits:
              memory: 1Gi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
  status: {}