apiVersion: v1
kind: Template
metadata:
  annotations:
    description: ${SERVICE_NAME} image-stream config template
  name: ${SERVICE_NAME}-image-stream-template
parameters:
- description: Name of the service
  displayName: Service Name
  name: SERVICE_NAME
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: ${SERVICE_NAME}